[tox]
envlist =
    py312
    py313
    py314

requires =
    tox-uv>=1.28

[testenv]
deps =
    pytest>=8
    pytest-cov>=5
    pytest-xdist>=3.5
commands =
    pytest tests -q -n auto --cov=lights_off --cov-fail-under=1
setenv =
    PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1
