import wx

class PollGui(wx.Dialog):
	def __init__(self):
		wx.Dialog.__init__(self, None, title="Compose poll", style=wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER)
		self.panel = wx.Panel(self)
		self.main_box = wx.BoxSizer(wx.VERTICAL)
		self.runfor_label = wx.StaticText(self.panel, -1, "Run Poll &for (Days)")
		self.main_box.Add(self.runfor_label, 0, wx.LEFT|wx.RIGHT|wx.TOP, 10)
		self.runfor = wx.SpinCtrl(self.panel, -1, min=1,max=7)
		self.main_box.Add(self.runfor, 0, wx.ALL, 10)
		self.runfor.SetFocus()
		self.opt1_label = wx.StaticText(self.panel, -1, "Option &1")
		self.main_box.Add(self.opt1_label, 0, wx.LEFT|wx.RIGHT|wx.TOP, 10)
		self.opt1 = wx.TextCtrl(self.panel, -1, "",style=wx.TE_DONTWRAP, size=(400,-1))
		self.main_box.Add(self.opt1, 0, wx.ALL|wx.EXPAND, 10)
		self.opt2_label = wx.StaticText(self.panel, -1, "Option &2")
		self.main_box.Add(self.opt2_label, 0, wx.LEFT|wx.RIGHT|wx.TOP, 10)
		self.opt2 = wx.TextCtrl(self.panel, -1, "",style=wx.TE_DONTWRAP, size=(400,-1))
		self.main_box.Add(self.opt2, 0, wx.ALL|wx.EXPAND, 10)
		self.opt3_label = wx.StaticText(self.panel, -1, "Option &3")
		self.main_box.Add(self.opt3_label, 0, wx.LEFT|wx.RIGHT|wx.TOP, 10)
		self.opt3 = wx.TextCtrl(self.panel, -1, "",style=wx.TE_DONTWRAP, size=(400,-1))
		self.main_box.Add(self.opt3, 0, wx.ALL|wx.EXPAND, 10)
		self.opt4_label = wx.StaticText(self.panel, -1, "Option &4")
		self.main_box.Add(self.opt4_label, 0, wx.LEFT|wx.RIGHT|wx.TOP, 10)
		self.opt4 = wx.TextCtrl(self.panel, -1, "",style=wx.TE_DONTWRAP, size=(400,-1))
		self.main_box.Add(self.opt4, 0, wx.ALL|wx.EXPAND, 10)
		button_row = wx.BoxSizer(wx.HORIZONTAL)
		self.ok = wx.Button(self.panel, wx.ID_OK, "&OK")
		self.ok.SetDefault()
		button_row.Add(self.ok, 0, wx.ALL, 5)
		self.close = wx.Button(self.panel, wx.ID_CANCEL, "&Cancel")
		button_row.Add(self.close, 0, wx.ALL, 5)
		self.main_box.Add(button_row, 0, wx.ALL|wx.ALIGN_RIGHT, 5)
		self.panel.SetSizer(self.main_box)
		self.main_box.Fit(self.panel)
		self.Fit()
		self.SetMinSize(self.GetSize())
		self.Centre()
